create schema if not exists state;

create table
    if not exists state.state (
        id bigint generated by default as identity,
        state varchar(512) not null,
        created_at timestamp default current_timestamp
    )