create schema if not exists services;

create table if not exists services.service (
    id bigint generated by default as identity primary key,
    platform_id bigint not null references platforms.platform_information(id),
    name text not null,
    description text,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create table if not exists services.service_extends_service (
    id bigint generated by default as identity primary key,
    service_id bigint not null references services.service(id),
    service_extends_service_id bigint references services.service(id),
);

